### ISSUE TITLE
operating-hours has an invalid jsonConfig: 

### ISSUE THREAD

**Issue by Brainbug01** [BenAhrdt/ioBroker.operating-hours#75]
Admin v6.12.1 meldet beim öffnen des operating-hours Adapters:

```
operating-hours has an invalid jsonConfig: 
[{
"instancePath":"",
"schemaPath":"#/required",
"keyword":"required",
"params":{"missingProperty":"type"},
"message":"must have required property 'type'"
}]

```

**Comment by BenAhrdt** [comment]
OK, ich habe dies eben bei mehreren Adaptern gesehen.
Eventuell auch ein "Fehler" im checken vom shema.
Ich habe es mal als issue zum react shema weiter gegeben:

[https://github.com/ioBroker/adapter-react-v5/issues/203](https://github.com/ioBroker/adapter-react-v5/issues/203)

**Comment by BenAhrdt** [comment]
@Brainbug01 fiexed in 1.0.5
